#pragma config(Sensor, dgtl7,  kill,           sensorDigitalIn)
#pragma config(Motor,  port1,           forkLift1,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftClaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightClaw,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          forkLift2,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
int hsp1 = 0; // up
int hsp2 = 0; // down
int hsp3 = 0; // left
int hsp4 = 0; // right
int spd = 10;
int end = 1;




while(end == 1) {
	if(vexRT[Btn7L] == 1){
			spd = 10;
		}
		if(vexRT[Btn7D] == 1){
			spd = 20;
		}
		if(vexRT[Btn7R] == 1){
			spd = 50;
		}
	  if ( vexRT[Ch1] < -50) {
				hsp1 = 4;
	  } else {
	 			hsp1 = 0;
	  }

		if ( vexRT[Ch1] > 50) {
				hsp2 = 4;
	  } else {
	  		hsp2 = 0;
		}
	  if ( vexRT[Ch2] > 50) {
				hsp3 = 2;
	  } else {
	  		hsp3 = 0;
		}
		if ( vexRT[Ch2] < -50) {
				hsp4 = 2;
		} else {
				hsp4 = 0;
	  }
	motor[frontRightMotor] = (hsp1 - hsp2 + hsp3 - hsp4)*spd;
	motor[frontLeftMotor] = (hsp1 - hsp2 - hsp3 + hsp4)*spd;
		//Forklift up
	if (vexRT[Btn5D] == 1){
			motor[forkLift1] = 127;
			motor[forkLift2] = 127;
		}
		//Forklift Down
		else if (vexRT[Btn5U] == 1){
			motor[forkLift1] = -127;
			motor[forkLift2] = -127;
		}
		else{
			motor[forkLift1] = 0;
			motor[forkLift2] = 0;
		}


			//Claw up
	if (vexRT[Btn6D] == 1){
			motor[leftClaw] = 127;
			motor[rightClaw] = 127;
		}
		//Claw Down
		else if (vexRT[Btn6U] == 1){
			motor[leftClaw] = -127;
			motor[rightClaw] = -127;
		}
		else{
			motor[leftClaw] = 0;
			motor[rightClaw] = 0;
		}
		if (SensorValue[kill] != 1) {
			end = 0;
	  }

}


}
